  METHOD SET_GERAR.

    SELECT SINGLE COD_LINHA, NOME_LINHA, VAL_UNIT, WAERS INTO @DATA(LWA_ZEQA_TABELA_LINHA)
      FROM ZEQA_TABELA_LINH
     WHERE COD_LINHA EQ @IN_CODLINHA.

    IF SY-SUBRC EQ 0.
      OUT_LINE = LWA_ZEQA_TABELA_LINHA-COD_LINHA && ';' && LWA_ZEQA_TABELA_LINHA-NOME_LINHA && ';' && LWA_ZEQA_TABELA_LINHA-VAL_UNIT && ';' && LWA_ZEQA_TABELA_LINHA-WAERS.
    ENDIF.

  ENDMETHOD.
