****************************************************************																																
*   THIS FILE IS GENERATED BY THE SCREEN PAINTER.              *																																
*   NEVER CHANGE IT MANUALLY, PLEASE !                         *																																
****************************************************************																																
%_DYNPRO																																
ZEQA_COCKPIT_STATUS																																
9001																																
750																																
             40																																
%_HEADER																																
ZEQA_COCKPIT_STATUS                     9001 9001     15 62192 37  0  0 27132  0G P                              20230712093707																																
%_DESCRIPTION																																
Tela de bloqueio e desbloqueio																																
%_FIELDS																																
QDSTATUS		CHAR	 59	00	00	00	30	00	  2	  5		  0	  0	  0		 14	R				  0	  0	101							Função_para_Ativar/Bloquear_Cartão________________________		
LBCPF	0	CHAR	 13	00	00	00	30	00	  4	  7		  0	  0	  0		  0					  0	  0								Número_do_CPF		
ZEQA_TABELA_GRDR-NUM_CARTAO	N	NUMC	 10	80	00	80	00	00	  5	  7		  0	  0	  0		 17					 20	  0								__________	 DL	
BTNPESQUISAR		CHAR	  9	00	00	00	30	00	  5	 25		  0	  0	  0		  0	P				  0	  0	102							Pesquisar	                                                                                                                                                                        FFIND	
LBCARTAO	0	CHAR	 16	00	00	00	30	00	  7	  7		  0	  0	  0		  0					  0	  0								Numero_do_Cartão		
LBCRED	0	CHAR	 18	00	00	00	30	00	  7	 26		  0	  0	  0		  0					  0	  0								Créditos_do_Cartão		
GWA_ZEQA_TABELA_GRDR-NUM_CARTAO	N	NUMC	 10	80	00	80	30	00	  8	  7		  0	  0	  0		  0					  0	  0								__________		
GWA_ZEQA_TABELA_GRDR-CREDITO	P	DEC	 24	80	00	80	30	00	  8	 26		  0	  0	  0		  0					  0	  0								________________________		
LBSTATUS	0	CHAR	 12	00	00	00	30	00	 10	  7		  0	  0	  0		  0					  0	  0								Status_atual		
GWA_ZEQA_TABELA_GRDR-CART_BLOCK_AT	C	CHAR	 10	80	00	80	30	00	 11	  7		  0	  0	  0		  0					  0	  0								__________		
BTNATIVA		CHAR	  6	00	00	00	30	00	 12	  7		  0	  0	  0		  0	P				  0	  0	103							Ativar	                                                                                                                                                                        FATIVA	
BTNBLOQUEIA		CHAR	  8	00	00	00	30	00	 12	 14		  0	  0	  0		  0	P				  0	  0	104							Bloquear	                                                                                                                                                                        FBLOCK	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE STATUS_9001.																																
*																																
PROCESS AFTER INPUT.																																
  MODULE USER_COMMAND_9001.																																
%_PARAMS																																
																																
